version: "3.9"

services:

  product-service:
    build:
      context: ./Microservices/product-service
      dockerfile: docker.yml

    ports:
      - "3001:3001"
    networks:
      - microservices-network

  user-service:
    build:
      context: ./Microservices/user-service
      dockerfile: docker.yml
    ports:
      - "3000:3000"
    networks:
      - microservices-network

  gateway-service:
    build:
      context: ./Microservices/gateway-service
      dockerfile: docker.yml
    ports:
      - "3003:3003"
    networks:
      - microservices-network

  order-service:
    build:
      context: ./Microservices/order-service
      dockerfile: docker.yml
    ports:
      - "3002:3002"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
